# Generated by Django 5.1.4 on 2025-05-08 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
        ('orders', '0003_alter_order_options_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого со скидкой'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discount', verbose_name='Скидка'),
        ),
    ]
