# Generated by Django 5.1.4 on 2025-05-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discounted_total_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, help_text='Загрузите PDF или изображение счёта', null=True, upload_to='orders/invoices/%Y/%m/%d/', verbose_name='Счёт-фактура'),
        ),
    ]
