# Generated by Django 5.1.4 on 2025-06-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='product',
            new_name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
