# Generated by Django 5.1.4 on 2025-05-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_page',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу производителя'),
        ),
    ]
