# Generated by Django 5.1.4 on 2025-06-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
